title: Mist of Pandaria
description: Guides and tips & tricks
theme: just-the-docs

url: https://moonwell-poolparty.github.io/wow-mop-guides
color_scheme: dark

callouts:
  tank:
    title: Tank
    color: indigo-glow
  healer:
    title: Healer
    color: teal-glow
  melee:
    title: Melee DPS
    color: magenta-glow
  ranged:
    title: Ranged DPS
    color: magenta-glow
  raidlead:
    title: Raidlead
    color: magenta-glow
  everyone:
    title: Everyone
    color: amber-glow
  normal:
    title: Normal
    color: indigo-glow
  heroic:
    title: Heroic
    color: amber-glow

callouts_opacity: 0.75
