title: Mist of Pandaria
description: Guides and tips & tricks
theme: just-the-docs

url: https://moonwell-poolparty.github.io/wow-mop-guides
color_scheme: dark

callouts:
  tank:
    title: Tank
    color: "#1976D2"   # lighter blue
  healer:
    title: Healer
    color: "#4CAF50"   # green
  melee:
    title: Melee DPS
    color: "#EF5350"   # softer red
  ranged:
    title: Ranged DPS
    color: "#E57373"   # lighter red
  raidlead:
    title: Raidlead
    color: "#FF1744"   # brightest red
  everyone:
    title: Everyone
    color: "#FFEB3B"   # yellow
  normal:
    title: Normal
    color: "#0D47A1"   # darker blue
  heroic:
    title: Heroic
    color: "#FFC107"   # amber/yellow
