title: Mist of Pandaria
description: Guides and tips & tricks
theme: just-the-docs

url: https://moonwell-poolparty.github.io/wow-mop-guides
color_scheme: dark

callouts:
  tank:
    title: Tank
    color: '#1976D2'
  healer:
    title: Healer
    color: '#4CAF50'
  melee:
    title: Melee DPS
    color: '#EF5350'
  ranged:
    title: Ranged DPS
    color: '#E57373'
  raidlead:
    title: Raidlead
    color: '#FF1744'
  everyone:
    title: Everyone
    color: '#FFEB3B'
  normal:
    title: Normal
    color: '#0D47A1'
  heroic:
    title: Heroic
    color: '#FFC107'
