title: Mist of Pandaria
description: Guides and tips & tricks
theme: just-the-docs

url: https://moonwell-poolparty.github.io/wow-mop-guides

callouts:
  tank:
    title: Tank
    color: blue
  healer:
    title: Healer
    color: green
  melee:
    title: Melee DPS
    color: red
  ranged:
    title: Ranged DPS
    color: red
  raidlead:
    title: Raidlead
    color: red
  everyone:
    title: Everyone
    color: yellow
  normal:
    title: Normal
    color: blue
  heroic:
    title: Heroic
    color: yellow
